version: "3.7"


services:
  energy:
    image: "energy:latest"
    restart: always
    build:
      target: development_build
      context: .
      dockerfile: ./Dockerfile
      cache_from:
        - "energy:latest"
      args:
        DJANGO_ENV: ${DJANGO_ENV:-production}
    command: demo_server
    ports:
      - "8888:8000"
#    env_file: .env.local
    environment:
      STATIC_ROOT: /code/static
#      DJANGO_ENV: development
      DJANGO_ENV: production

#    volumes:
#      - ./db.sqlite3:/code/db.sqlite3
#
#  redis:
#    image: redis:7.0.11-alpine
#    restart: always
#    ports:
#      - "6379:6379"
#
#  db:
#    image: postgres:14-alpine
#    restart: always
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER:-postgres}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
#      POSTGRES_DB: ${POSTGRES_DB:-postgres}
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./db_data:/var/lib/postgresql/data