# Generated by Django 5.0.4 on 2024-04-07 09:00

import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import energy.tariffs.models
import types
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivationRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "parameter",
                    models.CharField(
                        choices=[("date", "Date"), ("time", "Time"), ("weekday", "Weekday"), ("consumed", "Consumed")],
                        max_length=255,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("eq", "Eq"),
                            ("in", "In"),
                            ("not_in", "Not in"),
                            ("between", "Between"),
                            ("not_between", "Not between"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    django_pydantic_field.fields.PydanticSchemaField(
                        blank=True,
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        schema=django_pydantic_field.compat.django.GenericContainer(
                            typing.Union, (energy.tariffs.models.ConditionValue, types.NoneType)
                        ),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TariffGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "tariff_group",
            },
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("unit_price", models.DecimalField(decimal_places=10, max_digits=15)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[("KW", "Kw"), ("kWh", "Kwh"), ("kVA", "Kva"), ("days", "Days"), ("fixed", "Fixed")],
                        max_length=255,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("consumption_coefficient", models.DecimalField(decimal_places=5, default=1, max_digits=10)),
                ("activation_rules", models.ManyToManyField(related_name="tariffs", to="tariffs.activationrule")),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="suppliers.energysupplier",
                    ),
                ),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tariffs.tariffgroup")),
            ],
            options={
                "db_table": "tariff",
                "unique_together": {("priority", "group")},
            },
        ),
    ]
