# Generated by Django 5.0.4 on 2024-04-07 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyQuantile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("type", models.CharField(choices=[("KW", "Kw"), ("kWh", "Kwh"), ("kVA", "Kva")], max_length=255)),
                ("value", models.DecimalField(decimal_places=10, max_digits=15)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_quantiles",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "energy_quantile",
            },
        ),
        migrations.AddConstraint(
            model_name="energyquantile",
            constraint=models.CheckConstraint(
                check=models.Q(("start__lte", models.F("end"))), name="start_less_than_or_equal_to_end"
            ),
        ),
    ]
