# Generated by Django 5.0.4 on 2024-04-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consumption", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EnergyQuantile",
            new_name="EnergyConsumptionRecord",
        ),
    ]
