# Generated by Django 5.0.4 on 2024-04-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumption", "0002_rename_energyquantile_energyconsumptionrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyconsumptionrecord",
            name="value",
            field=models.DecimalField(decimal_places=10, max_digits=15, verbose_name="Consumed value"),
        ),
    ]
