# Generated by Django 5.0.4 on 2024-04-07 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="demo_bill_from",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 12, 31, 13, 0, tzinfo=datetime.timezone.utc), null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="demo_bill_to",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 31, 13, 0, tzinfo=datetime.timezone.utc), null=True
            ),
        ),
    ]
